name: Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  DB_CONNECTION_STRING: mongodb+srv://<DB_USER>:<PASSWORD>@cluster0.ezbuktp.mongodb.net/<DB_NAME>?retryWrites=true&w=majority
  PORT: 8000
jobs:
  test:
    environment: Test
    runs-on: self-hosted
    steps:
      - name: Setup nodejs 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Get Code
        uses: actions/checkout@v3
      - name: Create config.env file
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" > __tests__/config.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> __tests__/config.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> __tests__/config.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> __tests__/config.env
          echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> __tests__/config.env
          echo "DB_CONNECTION_STRING=${{ env.DB_CONNECTION_STRING }}" >> __tests__/config.env
          echo "PORT=${{ env.PORT }}" >> __tests__/config.env
        working-directory: ${{ github.workspace }}
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test code
        id: run-tests
        run: npm test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json

  build:
    needs: test
    environment: Production
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install node js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Create config.env file
        run: |
          echo "DB_NAME=${{ secrets.DB_NAME }}" > config.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> config.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> config.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> config.env
          echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> config.env
          echo "DB_CONNECTION_STRING=${{ env.DB_CONNECTION_STRING }}" >> config.env
          echo "PORT=${{ env.PORT }}" >> config.env
        working-directory: ${{ github.workspace }}
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build project
        run: npm run build --if-present
      - name: Restart devops-assignment-01
        run: sudo pm2 restart devops-assignment-01
